server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${JDBC.URL}]
    username: ${JDBC.USERNAME}
    password: ${JDBC.PASSWORD}
  redis:
    host: ${REDIS.HOST}
    port: ${REDIS.PORT}
    username: ${REDIS.USRENAME}
    password: ${REDIS.PASSWORD}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
